services:
  unity-tts-frontend:
    image: ghcr.io/sieteunoseis/unity-tts-frontend:master
    container_name: unity-tts-frontend
    ports:
      - "3001:80" # Map port 3000 on host to port 80 in container
    networks:
      - unity-network
    env_file:
      - .env

  unity-tts-backend:
    image: ghcr.io/sieteunoseis/unity-tts-backend:master
    container_name: unity-tts-backend
    volumes:
      - ./data:/usr/src/app/data
      - ./db:/usr/src/app/db
    expose:
      - "5000"
    user: "${UID:-1000}:${GID:-1000}"  # Use host user's UID/GID
    networks:
      - unity-network
    env_file:
      - .env

networks:
  unity-network:
    driver: bridge