services:
  unity-tts-frontend:
    image: ghcr.io/sieteunoseis/unity-tts-frontend:master
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in container
    networks:
      - unity-network
    environment:
      - VITE_BACKEND_URL=http://unity-tts-backend:5001
    env_file:
      - .env

  unity-tts-backend:
    image: ghcr.io/sieteunoseis/unity-tts-backend:master
    volumes:
      - ./data:/usr/src/app/data
      - ./db:/usr/src/app/db
    expose:
      - "5001"
    networks:
      - unity-network
    environment:
      - PORT=5001
    env_file:
      - .env

networks:
  unity-network:
    driver: bridge