services:
  frontend:
    build:
      context: ./frontend # Path to the front Dockerfile
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in container
    environment:
      - VITE_BACKEND_PORT=5001

  backend:
    build:
      context: ./backend # Path to the backend Dockerfile
    ports:
      - "5001:5001" # Map port 5001 on host to port 5001 in container
    environment:
      - TABLE_COLUMNS=name,hostname,username,password,version # Environment variable for the table columns. Update as needed for your project.
